-- MySQL Script generated by MySQL Workbench
-- mar 24 ene 2017 11:59:47 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema creditcard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema creditcard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creditcard` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `creditcard` ;

-- -----------------------------------------------------
-- Table `creditcard`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(20) NOT NULL,
  `nivel` INT NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NOT NULL,
  `jefe_id_usuario` INT NOT NULL,
  `us_nombre` VARCHAR(30) NOT NULL,
  `us_apat` VARCHAR(30) NOT NULL,
  `us_amat` VARCHAR(30) NOT NULL,
  `us_celular` VARCHAR(30) NULL,
  `us_email` VARCHAR(45) NULL,
  `us_user` VARCHAR(15) NOT NULL,
  `us_pass` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_tipo_user_idx` (`id_tipo_usuario` ASC),
  INDEX `fk_usuario_usuario1_idx` (`jefe_id_usuario` ASC),
  UNIQUE INDEX `us_user_UNIQUE` (`us_user` ASC),
  CONSTRAINT `fk_usuarios_tipo_user`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `creditcard`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario1`
    FOREIGN KEY (`jefe_id_usuario`)
    REFERENCES `creditcard`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`situacionAgen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`situacionAgen` (
  `id_situacionAgen` INT NOT NULL AUTO_INCREMENT,
  `situacionAgen` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_situacionAgen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`statusFinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`statusFinal` (
  `id_statusFinal` INT NOT NULL AUTO_INCREMENT,
  `statusFinal` VARCHAR(30) NULL,
  PRIMARY KEY (`id_statusFinal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`universidad` (
  `id_universidad` INT NOT NULL,
  `universidad` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_universidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`lugarApertura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`lugarApertura` (
  `id_lugarApertura` INT NOT NULL AUTO_INCREMENT,
  `lugarApertura` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_lugarApertura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`localidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`localidad` (
  `id_localidad` INT NOT NULL AUTO_INCREMENT,
  `localidad` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_localidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`solicitud` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `folio` VARCHAR(30) NOT NULL,
  `sol_nombre` VARCHAR(30) NOT NULL,
  `sol_apat` VARCHAR(30) NOT NULL,
  `sol_amat` VARCHAR(30) NOT NULL,
  `lada` VARCHAR(10) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(50) NOT NULL,
  `id_lugarApertura` INT NOT NULL,
  `id_localidad` INT NOT NULL,
  `dictamen` ENUM('APROBADO', 'APROBADO PRECLAS', 'PREAPROBADO', 'DECLINADO', 'RECHAZADO') NULL,
  `semaforo` ENUM('S/N', 'ROJO', 'VERDE', 'AMBAR', 'AMARILLO', 'AZUL') NULL,
  `fechaCaptura` DATE NOT NULL,
  `fechaDecision` DATE NOT NULL,
  `id_situacionAgen` INT NOT NULL,
  `situacionSol` ENUM('EN PROCESO AGENCIA', 'EN PROCESO BANCO', 'NO RECHAZADO', 'RECHAZADO') NULL,
  `id_statusFinal` INT NOT NULL,
  `causaRechazo` VARCHAR(80) NULL,
  `fechaCarga` DATE NOT NULL,
  `fechaVigencia` DATE NOT NULL,
  `cuestionario` ENUM('SI','NO', 'NO NECESITA') NOT NULL,
  `tokenEfi` VARCHAR(20) NOT NULL,
  `formalizada` ENUM('SI','NO') NOT NULL,
  `fechaFormal` DATE NOT NULL,
  `id_universidad` INT NOT NULL,
  `codigoCliente` VARCHAR(20) NOT NULL,
  `puntoVenta` VARCHAR(60) NULL,
  `observacion` TEXT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_solicitud_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_solicitud_producto1_idx` (`id_producto` ASC),
  UNIQUE INDEX `folio_UNIQUE` (`folio` ASC),
  INDEX `fk_solicitud_situacionAgen1_idx` (`id_situacionAgen` ASC),
  INDEX `fk_solicitud_statusFinal1_idx` (`id_statusFinal` ASC),
  INDEX `fk_solicitud_universidad1_idx` (`id_universidad` ASC),
  INDEX `fk_solicitud_lugarApertura1_idx` (`id_lugarApertura` ASC),
  INDEX `fk_solicitud_localidad1_idx` (`id_localidad` ASC),
  CONSTRAINT `fk_solicitud_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `creditcard`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `creditcard`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_situacionAgen1`
    FOREIGN KEY (`id_situacionAgen`)
    REFERENCES `creditcard`.`situacionAgen` (`id_situacionAgen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_statusFinal1`
    FOREIGN KEY (`id_statusFinal`)
    REFERENCES `creditcard`.`statusFinal` (`id_statusFinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_universidad1`
    FOREIGN KEY (`id_universidad`)
    REFERENCES `creditcard`.`universidad` (`id_universidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_lugarApertura1`
    FOREIGN KEY (`id_lugarApertura`)
    REFERENCES `creditcard`.`lugarApertura` (`id_lugarApertura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_localidad1`
    FOREIGN KEY (`id_localidad`)
    REFERENCES `creditcard`.`localidad` (`id_localidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`referencia` (
  `id_referencia` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `ref_nombre` VARCHAR(30) NOT NULL,
  `ref_apat` VARCHAR(30) NOT NULL,
  `ref_amat` VARCHAR(30) NOT NULL,
  `ref_telCasa` VARCHAR(30) NULL,
  `ref_telOp` VARCHAR(30) NULL,
  PRIMARY KEY (`id_referencia`),
  INDEX `fk_referencia_solicitud1_idx` (`id_solicitud` ASC),
  CONSTRAINT `fk_referencia_solicitud1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `creditcard`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`financiamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`financiamiento` (
  `id_financiamiento` INT NOT NULL AUTO_INCREMENT,
  `financiamiento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_financiamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`zero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`zero` (
  `id_zero` INT NOT NULL,
  `id_solicitud` INT NOT NULL,
  `universidad` VARCHAR(45) NULL,
  `campus` VARCHAR(45) NULL,
  `carrera` VARCHAR(45) NULL,
  `colegiatura` FLOAT NULL,
  `id_financiamiento` INT NOT NULL,
  `ingresoFam` FLOAT NULL,
  `procentajeBeca` FLOAT NULL,
  `gradoEsc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_zero`),
  INDEX `fk_zero_solicitud1_idx` (`id_solicitud` ASC),
  INDEX `fk_zero_financiamiento1_idx` (`id_financiamiento` ASC),
  CONSTRAINT `fk_zero_solicitud1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `creditcard`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zero_financiamiento1`
    FOREIGN KEY (`id_financiamiento`)
    REFERENCES `creditcard`.`financiamiento` (`id_financiamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
