-- MySQL Script generated by MySQL Workbench
-- vie 20 ene 2017 19:38:01 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema creditcard
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema creditcard
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `creditcard` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `creditcard` ;

-- -----------------------------------------------------
-- Table `creditcard`.`tipo_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`tipo_usuario` (
  `id_tipo_usuario` INT NOT NULL AUTO_INCREMENT,
  `tipo_usuario` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_tipo_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_tipo_usuario` INT NOT NULL,
  `jefe_id_usuario` INT NOT NULL,
  `us_nombre` VARCHAR(30) NOT NULL,
  `us_apat` VARCHAR(30) NOT NULL,
  `us_amat` VARCHAR(30) NOT NULL,
  `us_celular` VARCHAR(30) NULL,
  `us_email` VARCHAR(45) NULL,
  `us_user` VARCHAR(15) NOT NULL,
  `us_pass` VARCHAR(35) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_usuarios_tipo_user_idx` (`id_tipo_usuario` ASC),
  INDEX `fk_usuario_usuario1_idx` (`jefe_id_usuario` ASC),
  UNIQUE INDEX `us_user_UNIQUE` (`us_user` ASC),
  CONSTRAINT `fk_usuarios_tipo_user`
    FOREIGN KEY (`id_tipo_usuario`)
    REFERENCES `creditcard`.`tipo_usuario` (`id_tipo_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_usuario1`
    FOREIGN KEY (`jefe_id_usuario`)
    REFERENCES `creditcard`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`producto` (
  `id_producto` INT NOT NULL AUTO_INCREMENT,
  `producto` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`semaforo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`semaforo` (
  `id_semaforo` INT NOT NULL,
  `semaforo` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_semaforo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`situacionAgen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`situacionAgen` (
  `id_situacionAgen` INT NOT NULL AUTO_INCREMENT,
  `situacionAgen` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`id_situacionAgen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`situacionSol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`situacionSol` (
  `id_situacionSol` INT NOT NULL AUTO_INCREMENT,
  `situacionSol` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_situacionSol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`statusFinal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`statusFinal` (
  `id_statusFinal` INT NOT NULL AUTO_INCREMENT,
  `statusFinal` VARCHAR(30) NULL,
  PRIMARY KEY (`id_statusFinal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`causaRechazo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`causaRechazo` (
  `id_causaRechazo` INT NOT NULL AUTO_INCREMENT,
  `causaRechazo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_causaRechazo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`universidad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`universidad` (
  `id_universidad` INT NOT NULL,
  `universidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_universidad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`puntoVenta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`puntoVenta` (
  `id_puntoVenta` INT NOT NULL AUTO_INCREMENT,
  `puntoVenta` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_puntoVenta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`solicitud`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`solicitud` (
  `id_solicitud` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_producto` INT NOT NULL,
  `id_semaforo` INT NOT NULL,
  `folio` VARCHAR(30) NOT NULL,
  `sol_nombre` VARCHAR(30) NOT NULL,
  `sol_apat` VARCHAR(30) NOT NULL,
  `sol_amat` VARCHAR(30) NOT NULL,
  `lada` VARCHAR(10) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(50) NOT NULL,
  `fechaCaptura` DATE NOT NULL,
  `lugar_apertura` VARCHAR(80) NOT NULL,
  `localidad` VARCHAR(80) NOT NULL,
  `observacion` TEXT NULL,
  `fechaDecision` DATE NULL,
  `id_situacionAgen` INT NOT NULL,
  `id_situacionSol` INT NOT NULL,
  `id_statusFinal` INT NOT NULL,
  `id_causaRechazo` INT NOT NULL,
  `fechaCarga` DATE NOT NULL,
  `fechaVigencia` DATE NOT NULL,
  `cuestionario` ENUM('SI','NO', 'NO NECESITA') NOT NULL,
  `tokenEfi` VARCHAR(20) NOT NULL,
  `formalizada` ENUM('SI','NO') NOT NULL,
  `fechaFormal` DATE NOT NULL,
  `id_universidad` INT NOT NULL,
  `codigoCliente` VARCHAR(20) NOT NULL,
  `id_puntoVenta` INT NOT NULL,
  `dictamen` ENUM('APROBADO', 'APROBADO PRECLAS') NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_solicitud_usuario1_idx` (`id_usuario` ASC),
  INDEX `fk_solicitud_producto1_idx` (`id_producto` ASC),
  INDEX `fk_solicitud_semaforo1_idx` (`id_semaforo` ASC),
  UNIQUE INDEX `folio_UNIQUE` (`folio` ASC),
  INDEX `fk_solicitud_situacionAgen1_idx` (`id_situacionAgen` ASC),
  INDEX `fk_solicitud_situacionSol1_idx` (`id_situacionSol` ASC),
  INDEX `fk_solicitud_statusFinal1_idx` (`id_statusFinal` ASC),
  INDEX `fk_solicitud_causaRechazo1_idx` (`id_causaRechazo` ASC),
  INDEX `fk_solicitud_universidad1_idx` (`id_universidad` ASC),
  INDEX `fk_solicitud_puntoVenta1_idx` (`id_puntoVenta` ASC),
  CONSTRAINT `fk_solicitud_usuario1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `creditcard`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_producto1`
    FOREIGN KEY (`id_producto`)
    REFERENCES `creditcard`.`producto` (`id_producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_semaforo1`
    FOREIGN KEY (`id_semaforo`)
    REFERENCES `creditcard`.`semaforo` (`id_semaforo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_situacionAgen1`
    FOREIGN KEY (`id_situacionAgen`)
    REFERENCES `creditcard`.`situacionAgen` (`id_situacionAgen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_situacionSol1`
    FOREIGN KEY (`id_situacionSol`)
    REFERENCES `creditcard`.`situacionSol` (`id_situacionSol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_statusFinal1`
    FOREIGN KEY (`id_statusFinal`)
    REFERENCES `creditcard`.`statusFinal` (`id_statusFinal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_causaRechazo1`
    FOREIGN KEY (`id_causaRechazo`)
    REFERENCES `creditcard`.`causaRechazo` (`id_causaRechazo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_universidad1`
    FOREIGN KEY (`id_universidad`)
    REFERENCES `creditcard`.`universidad` (`id_universidad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_puntoVenta1`
    FOREIGN KEY (`id_puntoVenta`)
    REFERENCES `creditcard`.`puntoVenta` (`id_puntoVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`referencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`referencia` (
  `id_referencia` INT NOT NULL AUTO_INCREMENT,
  `id_solicitud` INT NOT NULL,
  `ref_nombre` VARCHAR(30) NOT NULL,
  `ref_apat` VARCHAR(30) NOT NULL,
  `ref_amat` VARCHAR(30) NOT NULL,
  `ref_telCasa` VARCHAR(30) NULL,
  `ref_telOp` VARCHAR(30) NULL,
  PRIMARY KEY (`id_referencia`),
  INDEX `fk_referencia_solicitud1_idx` (`id_solicitud` ASC),
  CONSTRAINT `fk_referencia_solicitud1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `creditcard`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`financiamiento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`financiamiento` (
  `id_financiamiento` INT NOT NULL,
  `financiamiento` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`id_financiamiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `creditcard`.`zero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `creditcard`.`zero` (
  `id_zero` INT NOT NULL,
  `id_solicitud` INT NOT NULL,
  `universidad` VARCHAR(45) NULL,
  `campus` VARCHAR(45) NULL,
  `carrera` VARCHAR(45) NULL,
  `colegiatura` FLOAT NULL,
  `id_financiamiento` INT NOT NULL,
  `ingresoFam` FLOAT NULL,
  `procentajeBeca` FLOAT NULL,
  `gradoEsc` VARCHAR(45) NULL,
  PRIMARY KEY (`id_zero`),
  INDEX `fk_zero_solicitud1_idx` (`id_solicitud` ASC),
  INDEX `fk_zero_financiamiento1_idx` (`id_financiamiento` ASC),
  CONSTRAINT `fk_zero_solicitud1`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `creditcard`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_zero_financiamiento1`
    FOREIGN KEY (`id_financiamiento`)
    REFERENCES `creditcard`.`financiamiento` (`id_financiamiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
